version: '3'

services:
  app:
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      DB_CONNECTION: "postgres://postgres:postgres@db/postgres"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./:/home/python
  db:
    image: postgres:11.5-alpine
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data:cached

volumes:
  pg-data: